[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "imagesize"
description = "Get image size from headers (BMP/PNG/JPEG/JPEG2000/GIF/TIFF/SVG/Netpbm/WebP/AVIF/HEIC/HEIF)"
authors = [
    {name = "Yoshiki Shibukawa", email="yoshiki@shibu.jp"},
]
readme = {file = "README.rst", content-type = "text/x-rst"}
license = "MIT"
dynamic = ["version"]
requires-python = ">=3.10"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.15",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: Multimedia :: Graphics"
]

[project.urls]
Repository = "https://github.com/shibukawa/imagesize_py"

[tool.setuptools.dynamic]
version = {attr = "imagesize.__version__"}
